[theme]

base = "light"

# Màu nền chính
backgroundColor = "#170352"

# Màu của widget
secondaryBackgroundColor = "#014589"

# Màu nút bấm
primaryColor = "#b80b02"

# Màu chữ các khung nhập liệu
textColor = "#ffff00"